dbp_relay_esign:
    qualified_signature:
        server_url: '%env(PDF_AS_WEB_QUALIFIED_URI)%'
        profiles:
            - name: default
              profile_id: SIGNATUREBLOCK_PROFILE1
              user_text:
                target_table: usercontent
                target_row: 1
                attach:
                    parent_table: main
                    child_table: user
                    parent_row: 2
              role: ROLE_SCOPE_PROFILE1
    advanced_signature:
        server_url: '%env(PDF_AS_WEB_ADVANCED_URI)%'
        profiles:
            - name: official
              key_id: profile2-key
              profile_id: SIGNATUREBLOCK_profile2
              user_text:
                target_table: usercontent
                target_row: 1
                attach:
                    parent_table: main
                    child_table: user
                    parent_row: 2
              role: ROLE_SCOPE_profile2
