dbp_relay_dispatch:
  database_url: '%env(DISPATCH_DATABASE_URL)%'
  service_url: '%env(DISPATCH_SERVICE_URL)%'
  sender_profile: '%env(DISPATCH_SENDER_PROFILE)%'
  sender_profile_version: '%env(DISPATCH_SENDER_PROFILE_VERSION)%'
  cert: '%env(base64:DISPATCH_CERT)%'
  cert_password: '%env(DISPATCH_CERT_PASSWORD)%'
  file_storage: '%env(DISPATCH_FILE_STORAGE)%'
  blob_base_url: '%env(DISPATCH_BLOB_BASE_URL)%'
  blob_bucket_id: '%env(DISPATCH_BLOB_BUCKET_ID)%'
  blob_key: '%env(DISPATCH_BLOB_KEY)%'
  authorization:
      roles:
          ROLE_USER: '(user.get("DISPATCH_WRITE_GROUPS", []) !== []) || (user.get("DISPATCH_READ_CONTENT_GROUPS", []) !== []) || (user.get("DISPATCH_READ_METADATA_GROUPS", []) !== [])'
      resource_permissions:
          ROLE_GROUP_READER_METADATA: 'resource.getIdentifier() in user.get("DISPATCH_READ_METADATA_GROUPS", [])'
          ROLE_GROUP_READER_CONTENT: 'resource.getIdentifier() in user.get("DISPATCH_READ_CONTENT_GROUPS", [])'
          ROLE_GROUP_WRITER: 'resource.getIdentifier() in user.get("DISPATCH_WRITE_GROUPS", [])'
          ROLE_GROUP_WRITER_READ_ADDRESS: 'resource.getIdentifier() in user.get("DISPATCH_WRITE_READ_ADDRESS_GROUPS", [])'
      attributes:
          GROUPS: 'user.get("DISPATCH_ALL_GROUPS", [])'
