dbp_relay_cabinet:
  database_url: '%env(CABINET_DATABASE_URL)%'
  blob:
    api_url: '%env(CABINET_BLOB_API_URL)%'
    bucket_id: '%env(CABINET_BLOB_BUCKET_ID)%'
    bucket_key: '%env(CABINET_BLOB_BUCKET_KEY)%'
    idp_url: '%env(CABINET_BLOB_IDP_URL)%'
    idp_client_id: '%env(CABINET_BLOB_IDP_CLIENT_ID)%'
    idp_client_secret: '%env(CABINET_BLOB_IDP_CLIENT_SECRET)%'
  typesense:
    api_url: '%env(CABINET_TYPESENSE_API_URL)%'
    api_key: '%env(CABINET_TYPESENSE_API_KEY)%'
  authorization:
    policies:
        ROLE_USER: 'true'
