dbp_relay_cabinet:
  database_url: '%env(CABINET_DATABASE_URL)%'
  blob_base_url: '%env(CABINET_BLOB_BASE_URL)%'
  blob_bucket_id: '%env(CABINET_BLOB_BUCKET_ID)%'
  blob_key: '%env(CABINET_BLOB_KEY)%'
  typesense_base_url: '%env(CABINET_TYPESENSE_BASE_URL)%'
  typesense_api_key: '%env(CABINET_TYPESENSE_API_KEY)%'
  authorization:
    policies:
        ROLE_USER: 'true'
