dbp_relay_esign:
    qualified_signature:
        server_url: '%env(PDF_AS_WEB_QUALIFIED_URI)%'
        callback_url: '%env(PDF_AS_WEB_QUALIFIED_STATIC_URI)%/callback.html'
        error_callback_url: '%env(PDF_AS_WEB_QUALIFIED_STATIC_URI)%/error.html'
        profiles:
            - name: default
              profile_id: SIGNATUREBLOCK_PROFILE1
              user_text_table: usercontent
              user_text_row: 1
              user_text_attach_parent: main
              user_text_attach_child: user
              user_text_attach_row: 2
              role: ROLE_SCOPE_PROFILE1
    advanced_signature:
        server_url: '%env(PDF_AS_WEB_ADVANCED_URI)%'
        profiles:
            - name: official
              key_id: profile2-key
              profile_id: SIGNATUREBLOCK_profile2
              user_text_table: usercontent
              user_text_row: 1
              user_text_attach_parent: main
              user_text_attach_child: user
              user_text_attach_row: 2
              role: ROLE_SCOPE_profile2
