dbp_relay_core_connector_ldap:
    connections:
        - identifier: DEFAULT
          host: '%env(LDAP_HOST)%'
          base_dn: '%env(LDAP_BASE_DN)%'
          username: '%env(LDAP_USER)%'
          password: '%env(LDAP_PASS)%'
    user_attribute_provider:
        ldap_connection: DEFAULT
