dbp_relay_mono_connector_payone:
  database_url: '%env(MONO_CONNECTOR_PAYONE_DATABASE_URL)%'
  payment_contracts:
    payone_contract:
      api_url: "%env(resolve:MONO_CONNECTOR_PAYONE_API_URL)%"
      api_key_id: "%env(MONO_CONNECTOR_PAYONE_API_KEY_ID)%"
      api_secret: "%env(MONO_CONNECTOR_PAYONE_API_SECRET)%"
      merchant_id: "%env(MONO_CONNECTOR_PAYONE_MERCHANT_ID)%"
      webhook_id: "%env(MONO_CONNECTOR_PAYONE_WEBHOOK_ID)%"
      webhook_secret: "%env(MONO_CONNECTOR_PAYONE_WEBHOOK_SECRET)%"
      payment_methods:
        creditcard:
          products: ['MasterCard', 'VISA']
