dbp_relay_cabinet_connector_campusonline:
  api_url: '%env(CABINET_CONNECTOR_CAMPUSONLINE_API_URL)%'
  client_id: '%env(CABINET_CONNECTOR_CAMPUSONLINE_CLIENT_ID)%'
  client_secret: '%env(CABINET_CONNECTOR_CAMPUSONLINE_CLIENT_SECRET)%'
  data_service_name_person_data: 'loc_apiDmsStudPersMv'
  data_service_name_active_studies: 'loc_apiDmsStudien'
