dbp_relay_mono:
  database_url: '%env(MONO_DATABASE_URL)'
  payment_session_timeout: 'PT1800S'
  payment_types:
    tuition_fee:
      service: 'Dbp\Relay\MonoConnectorCampusonlineBundle\Service\TuitionFeeService'
      payment_contracts:
        payunity_flex:
          service: 'Dbp\Relay\MonoConnectorPayunityBundle\Service\PayunityFlexService'
          payment_methods:
            - identifier: payunity_creditcard
              name: dbp_relay_mono.credit_card
              image: '/bundles/dbprelaymono/svg/credit-cards.svg'
  cleanup:
    - payment_status: prepared
      timeout_before: 'P1Y'
    - payment_status: started
      timeout_before: 'P1Y'
    - payment_status: cancelled
      timeout_before: 'P1Y'
