name: Update Flex endpoint

on:
    push:
        branches:
            - master

defaults:
    run:
        shell: bash

jobs:
    call-flex-update:
        uses: symfony/recipes/.github/workflows/callable-flex-update.yml@main
        with:
            branch: master
            versions_json: .github/versions.json
